services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # deploy:
    #   resources:
    #     limits:
    #       memory: 500M
    #     reservations:
    #       memory: 128M
      


